[package]
name = "RustSome"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easyinput = "0.1.0"
yahoo-weather = "0.2.0"
weather-info = "0.1.0"
time = "0.3.12"


